# Generated by Django 3.2.4 on 2021-06-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memetext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedannotation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
