# Generated by Django 3.2.4 on 2021-06-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memetext', '0003_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3image',
            name='last_assigned',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
