# Generated by Django 3.2.4 on 2021-06-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memetext', '0004_s3image_last_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='memo',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
