# Generated by Django 3.2.4 on 2021-06-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memetext', '0005_payment_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationbatch',
            name='batch_message',
            field=models.TextField(default='do you like memes?'),
            preserve_default=False,
        ),
    ]
