# Generated by Django 3.2.4 on 2021-06-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memetext', '0006_annotationbatch_batch_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationbatch',
            name='is_demo',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='assignedannotation',
            name='is_demo',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='controlannotation',
            name='is_demo',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_demo',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='payoutrate',
            name='is_demo',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='s3image',
            name='is_demo',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='testannotation',
            name='is_demo',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='annotationbatch',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='annotationbatch',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='assignedannotation',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='controlannotation',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payoutrate',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='s3image',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='testannotation',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
