# Generated by Django 3.2.4 on 2021-06-19 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memetext', '0007_auto_20210618_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlannotation',
            name='s3_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='memetext.s3image'),
        ),
    ]
