# Generated by Django 3.2.4 on 2021-06-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memetext', '0009_annotationbatch_batch_message_expanded'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationbatch',
            name='instructions_expanded',
            field=models.TextField(blank=True, default=''),
        ),
    ]
