# Generated by Django 3.2.4 on 2021-06-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memetext', '0010_annotationbatch_instructions_expanded'),
    ]

    operations = [
        migrations.AddField(
            model_name='testannotation',
            name='data',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
