# Generated by Django 3.2.4 on 2021-06-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memetext', '0012_crawledredditpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3image',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
