# Generated by Django 3.2.4 on 2021-06-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_item',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
