# Generated by Django 3.2.4 on 2021-06-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_userprofile_assigned_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_demo',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
