# Generated by Django 3.2.4 on 2021-06-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_userprofile_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
